services:
  - type: web
    name: sign-language-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: ENV
        value: production
    build:
      packages:
        - libgl1-mesa-dev
        - libglib2.0-0
