services:
  - type: web
    name: sign-language-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: ENV
        value: production
    build:
      packages:
        - libgl1-mesa-dev
        - libglib2.0-0
